// Generated by CoffeeScript 1.6.3
(function() {
  var Ex1Body, Ex1Headers, app, uuid;

  uuid = require("uuid");

  Ex1Headers = {
    principal: "me@me.com",
    event_type: "hello.world"
  };

  Ex1Body = {
    foo: "bar",
    bar: 123,
    foobar: ["foo", "bar", 123]
  };

  app = angular.module('AmqpApp', []);

  app.controller('MainCtrl', function($scope) {
    var amqpConnection, message_handler;
    $scope.id_box = uuid.v4();
    $scope.useSample = function() {
      $scope.header_box = JSON.stringify(Ex1Headers, void 0, 4);
      return $scope.body_box = JSON.stringify(Ex1Body, void 0, 4);
    };
    $scope.useSample();
    $scope.messages = [];
    message_handler = function(message) {
      return $scope.$apply(function() {
        return $scope.messages.push(message);
      });
    };
    amqpConnection = new AmqpConnection(message_handler);
    $scope.usingHeartbeat = false;
    $scope.heartbeatOff = function() {
      amqpConnection.stopHeartbeat();
      return $scope.usingHeartbeat = false;
    };
    $scope.heartbeatOn = function() {
      amqpConnection.startHeartbeat();
      return $scope.usingHeartbeat = true;
    };
    $scope.clearMessages = function() {
      return $scope.messages.length = 0;
    };
    return $scope.publish = function() {
      var bjson, body, e1, e2, e3, headers;
      headers = {};
      try {
        headers = JSON.parse($scope.header_box);
      } catch (_error) {
        e1 = _error;
        alert("Invalid Headers input.");
        return;
      }
      headers.id = $scope.id_box;
      body = null;
      try {
        bjson = JSON.parse($scope.body_box);
        if (bjson != null) {
          body = bjson;
        }
      } catch (_error) {
        e2 = _error;
        body = {
          msg: $scope.body_box
        };
      }
      try {
        amqpConnection.publish(body, headers);
        return $scope.id_box = uuid.v4();
      } catch (_error) {
        e3 = _error;
        return alert("Error publishing message: " + e3);
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
